"use client"

import { ThemeProvider } from '@emotion/react'
import './globals.css'
import { Inter } from 'next/font/google'
import { theme } from '@/components/theme'

const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Phonebook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
